services:
  # Base de datos PostgreSQL
  - type: pserv
    name: lapsync-db
    plan: free
    env: docker
    region: oregon
    
  # Aplicaci√≥n Spring Boot
  - type: web
    name: lapsync
    runtime: java
    plan: free
    region: oregon
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -Dspring.profiles.active=prod -Dserver.port=$PORT -jar target/LapSyncApp-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: lapsync-db
          property: connectionString
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx512m"
